export const AVAILABLE_SKILLS = [
    "C#",
    "SQL",
    "Git",
    "Entity Framework",
    "FastAPI",
    "Python",
    "React",
    "Docker",
    "Psychology",
    "Neurobiologie",
    "Genetic Engineer",
    "Food Entomologist",
    "AI Ethics",
    "Combat AI",
    "Metaverse expert",
    "Cybersecurity",
    "Machine Learning",
    "Communication",
    "Leadership",
    "ExCIA",
    "ExDARPA",
    "ExBlackRock",
    "ExCDC"
];